Reversi4colorForm: Reversi4colorForm.ReversiPlay Class Reference
Reversi4colorForm.ReversiPlay Class Reference
リバーシプレイクラス
Public Member Functions
delegate void ViewMsgDlg (string title, string msg)
delegate void DrawSingle (int y, int x, int sts, int bk, string text)
delegate void CurColMsg (string text)
delegate void CurStsMsg (string text)
ReversiPlay ()
コンストラクタ
ReversiPlay Clone ()
コピー
void reversiPlay (int y, int x)
リバーシプレイ
void reversiPlaySub (int cpuEna, int tmpCol)
リバーシプレイサブ
void reversiPlayEnd ()
リバーシプレイ終了
void reversiPlayPass (int color)
リバーシプレイパス
int reversiPlayCpu (int color, int cpuEna)
リバーシプレイコンピューター
void drawUpdate (int assist)
マス描画更新
void drawUpdateForcibly (int assist)
マス描画強制更新
void reset ()
リセット処理
int getNextCol (int color)
次の色取得
int gameEndAnimExec ()
ゲーム終了アニメーション
void sendDrawMsg (int y, int x)
描画メッセージ送信
void sendDrawInfoMsg (int y, int x)
情報描画メッセージ送信
Properties
MyReversi mReversi [get, set]
ReversiSetting mSetting [get, set]
int mCurColor [get, set]
ReversiPoint [] mCpu [get, set]
ReversiPoint [] mEdge [get, set]
int mPassEnaB [get, set]
int mPassEnaW [get, set]
int mPassEnaL [get, set]
int mPassEnaR [get, set]
int mGameEndSts [get, set]
int mPlayLock [get, set]
ViewMsgDlg viewMsgDlg [get, set]
DrawSingle drawSingle [get, set]
CurColMsg curColMsg [get, set]
CurStsMsg curStsMsg [get, set]
Private Member Functions
void execMessage (int what, Object obj)
メッセージ
void ViewMsgDlgLocal (string title, string msg)
メッセージダイアログ
void DrawSingleLocal (int y, int x, int sts, int bk, string text)
1マス描画
void CurColMsgLocal (string text)
現在の色メッセージ
void CurStsMsgLocal (string text)
現在のステータスメッセージ
Private Attributes
MyReversi _mReversi
リバーシクラス
ReversiSetting _mSetting
リバーシ設定クラス
int _mCurColor = 0
現在の色
ReversiPoint [] _mCpu
CPU用ワーク
ReversiPoint [] _mEdge
CPU用角マスワーク
int _mPassEnaB = 0
黒のパス有効フラグ
int _mPassEnaW = 0
白のパス有効フラグ
int _mPassEnaL = 0
青のパス有効フラグ
int _mPassEnaR = 0
赤のパス有効フラグ
int _mGameEndSts = 0
ゲーム終了ステータス
int _mPlayLock = 0
プレイロック
ViewMsgDlg _viewMsgDlg = null
メッセージコールバック
DrawSingle _drawSingle = null
描画コールバック
CurColMsg _curColMsg = null
現在の色メッセージコールバック
CurStsMsg _curStsMsg = null
現在のステータスメッセージコールバック
System.Random r = new System.Random()
乱数
Detailed Description
リバーシプレイクラス
Definition at line 30 of file ReversiPlay.cs.
Constructor & Destructor Documentation
ReversiPlay()
Reversi4colorForm.ReversiPlay.ReversiPlay ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 144 of file ReversiPlay.cs.
Member Function Documentation
Clone()
ReversiPlay Reversi4colorForm.ReversiPlay.Clone ()
コピー
Returns
オブジェクトコピー
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 164 of file ReversiPlay.cs.
CurColMsgLocal()
void Reversi4colorForm.ReversiPlay.CurColMsgLocal (string text) private
現在の色メッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1089 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.execMessage().
CurStsMsgLocal()
void Reversi4colorForm.ReversiPlay.CurStsMsgLocal (string text) private
現在のステータスメッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1103 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.execMessage().
DrawSingleLocal()
void Reversi4colorForm.ReversiPlay.DrawSingleLocal (int y, int x, int sts, int bk, string text) private
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1075 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.execMessage().
drawUpdate()
void Reversi4colorForm.ReversiPlay.drawUpdate (int assist)
マス描画更新
Parameters
[in] int assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 685 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.reversiPlay(), and Reversi4colorForm.ReversiPlay.reversiPlayCpu().
drawUpdateForcibly()
void Reversi4colorForm.ReversiPlay.drawUpdateForcibly (int assist)
マス描画強制更新
Parameters
[in] int assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 718 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.reset(), and Reversi4colorForm.Reversi.Reversi_Resize().
execMessage()
void Reversi4colorForm.ReversiPlay.execMessage (int what, Object obj) private
メッセージ
Parameters
[in] int what
[in] var obj
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 955 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.drawUpdate(), Reversi4colorForm.ReversiPlay.drawUpdateForcibly(), Reversi4colorForm.ReversiPlay.gameEndAnimExec(), Reversi4colorForm.ReversiPlay.reset(), Reversi4colorForm.ReversiPlay.reversiPlay(), Reversi4colorForm.ReversiPlay.reversiPlayCpu(), Reversi4colorForm.ReversiPlay.reversiPlayEnd(), Reversi4colorForm.ReversiPlay.reversiPlaySub(), Reversi4colorForm.ReversiPlay.sendDrawInfoMsg(), and Reversi4colorForm.ReversiPlay.sendDrawMsg().
gameEndAnimExec()
int Reversi4colorForm.ReversiPlay.gameEndAnimExec ()
ゲーム終了アニメーション
Returns
ウェイト時間
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 825 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.reversiPlayEnd().
getNextCol()
public int Reversi4colorForm.ReversiPlay.getNextCol (int color)
次の色取得
Parameters
[in] int color 現在の色
Returns
次の色
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 806 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.reset(), Reversi4colorForm.ReversiPlay.reversiPlay(), and Reversi4colorForm.ReversiPlay.reversiPlaySub().
reset()
void Reversi4colorForm.ReversiPlay.reset ()
リセット処理
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 743 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.Reversi.button1_Click(), and Reversi4colorForm.Reversi.button2_Click().
reversiPlay()
void Reversi4colorForm.ReversiPlay.reversiPlay (int y, int x)
リバーシプレイ
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 179 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.Reversi.pictureBox_Click().
reversiPlayCpu()
int Reversi4colorForm.ReversiPlay.reversiPlayCpu (int color, int cpuEna)
リバーシプレイコンピューター
Parameters
[in] int color CPU色
[in] int cpuEna CPU有効フラグ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 407 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.reversiPlaySub().
reversiPlayEnd()
void Reversi4colorForm.ReversiPlay.reversiPlayEnd ()
リバーシプレイ終了
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 318 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.reversiPlay(), and Reversi4colorForm.ReversiPlay.reversiPlaySub().
reversiPlayPass()
void Reversi4colorForm.ReversiPlay.reversiPlayPass (int color)
リバーシプレイパス
Parameters
[in] int color パス色
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 383 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.reversiPlay(), and Reversi4colorForm.ReversiPlay.reversiPlaySub().
reversiPlaySub()
void Reversi4colorForm.ReversiPlay.reversiPlaySub (int cpuEna, int tmpCol)
リバーシプレイサブ
Parameters
[in] int cpuEna
[in] int tmpCol
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 277 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.reversiPlay().
sendDrawInfoMsg()
void Reversi4colorForm.ReversiPlay.sendDrawInfoMsg (int y, int x)
情報描画メッセージ送信
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 936 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.drawUpdate().
sendDrawMsg()
void Reversi4colorForm.ReversiPlay.sendDrawMsg (int y, int x)
描画メッセージ送信
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 917 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.drawUpdate(), Reversi4colorForm.ReversiPlay.gameEndAnimExec(), Reversi4colorForm.ReversiPlay.reversiPlay(), and Reversi4colorForm.ReversiPlay.reversiPlayCpu().
ViewMsgDlgLocal()
void Reversi4colorForm.ReversiPlay.ViewMsgDlgLocal (string title, string msg) private
メッセージダイアログ
Parameters
[in] string title タイトル
[in] string msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 1057 of file ReversiPlay.cs.
Referenced by Reversi4colorForm.ReversiPlay.reversiPlay(), and Reversi4colorForm.ReversiPlay.reversiPlayEnd().
The documentation for this class was generated from the following file:
Model/ReversiPlay.cs